### ISSUE TITLE
OntoNote Data？

### ISSUE THREAD

**Issue by seafire1991** [ljinstat/coreference_resolution#2]
Hi!
Where Can I get OntoNote Data? conll.cemantix.org/2012/data.html,the data here are incomplete, Is it necessary a member from LDC?

Best
Kong.

**Comment by ljinstat** [comment]
Hi Kong,

You have to be the member, or your institution is a member of LDC, because
LDC keeps the property.

Cheers,
Ling

seafire1991 <notifications@github.com> 于2019年1月7日周一 上午2:53写道：

**Comment by seafire1991** [comment]
Hi!
   Thanks for the quick reply!  I find a data from here in chinese: http://universaldependencies.org/.

**Comment by ljinstat** [comment]
HI!
I am not sure whether it is ontonotes 5.0. Have you verified it?

Ling

seafire1991 <notifications@github.com> 于2019年1月8日周二 下午3:06写道：

**Comment by seafire1991** [comment]
HI!
  This is another corpus for Dependency Parsing，not ontonotes 5.0, but can be used for my task,thanks~
